apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedule-bot-data
  namespace: bots
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
